- name: install EPEL repo
  yum: name=http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: install EPEL repo
  yum: name=http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: setup etckeeper
  yum: name=etckeeper state=present
  when: ansible_os_family == 'RedHat'

- name: setup git
  apt: name=git state=present
  when: ansible_os_family == 'Debian'

- name: setup etckeeper
  apt: name=etckeeper state=present
  when: ansible_os_family == 'Debian'

- name: put etckeeper config
  template: src=etckeeper/etckeeper.conf dest=/etc/etckeeper/etckeeper.conf owner=root group=root mode=0644
  when: ansible_os_family == 'Debian'

- name: check if a repo is initialized already
  command: bash -c "cd /etc && git status"
  ignore_errors: True
  register: result

- name: init etckeeper repo
  command: bash -c "etckeeper init && etckeeper commit \"Initial commit\""
  when: result|failed
